version: "3.9"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8080:8080"
    command: /start
  postgres:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:cached
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: celerybeat
    ports: []
    command: /start-celerybeat
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4444:4444"
    networks:
      - collabnet
  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    platform: linux/amd64
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=true
    networks:
      - collabnet

  chrome-debug:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    platform: linux/amd64
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=true
    ports:
      - "5900:5900"
    networks:
      - collabnet
  # elasticsearch:
  #   image: 'docker.elastic.co/elasticsearch/elasticsearch:8.5.3'
  #   container_name: elasticsearch
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - ES_JAVA_OPTS=-Xmx4g -Xms4g
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - '9200:9200'
networks:
  collabnet:
volumes:
  postgres_data: {}
