#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# python /app/manage.py collectstatic --no-input --clear
/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:8080 --chdir=/app -k uvicorn.workers.UvicornWorker